# The ID of your experiment 
EXPERIMENT: "ID"

# Whether to use the live speckle feature
USE_LIVE_SPECKLE: true
BUFFER_SIZE: 10

# What exposure time to use (in ms, can be < 0)
EXPOSURE_TIME: 15
# Analog gain of the camera, try to keep as low as possible
ANALOG_GAIN: 1
# Where should the data be saved - now determined by user input in cam control 
SAVE_DIR: 'C:\\Data\\WF_Recordings'

# Whether the data should be binned during the experiment
# raw data is huge (2048, 2048) images
BIN_EXP_LIVE: false
# What bin size is done (e.g., 4 means final image size will be 512, 512)
BIN_SIZE: 2
# Force a specific framerate even when the exposure is short
FORCE_FRAMERATE: false
# What framerate to be forced, make sure exposure time is < forced framerate
SPECIAL_FRAMERATE: 50


## Frame trigger mode settings
# The serial port of the RPi pico that will generate the camera's PWM signal
# If no pico is plugged in, set this to null
PICO_SERIAL_PORT: null # 'COM4'
# PWM frequency of the RPi pico, will be the framerate of the camera
PICO_PWM_FREQUENCY: 10
# What percentage of the square wave should be 'on' 50 is good
PICO_PWM_DUTY: 50

# Do not change this
UDP_TRIGGER_PORT: 1001