#Experiment config file
# Basic file for parameters of the experiment
# All delays in seconds
name: "RetinotopyFB"


# the delay before starting and after ending the experiment (black square comes on at half of this time)
experiment_delay: 8

generic_stimulus_parameters:
  pre_gap_dur: 2.0
  post_gap_dur: 3.0
  background: 0.0
  coordinate: degree
  block_iterations: 1 #30  #orginal is 20 # same as ds_display_iter or repeat in ab lab

KSstimAllDir:
  ks_square_size: 25.0
  ks_square_center: [0, 0]
  ks_flicker_frame: 10
  ks_sweep_width: 20.0
  ks_step_width: 0.15
  ks_sweep_frame: 1 
  ks_iteration: 1 # don't change this



trial_params_columns: ["clock_time", "block_iter", "null", "null"]
